# Generated by Django 3.1.7 on 2021-03-21 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.BigIntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despejos.cor')),
            ],
        ),
        migrations.CreateModel(
            name='LayerDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_visualizacao', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('legendas', models.ManyToManyField(to='despejos.Legenda')),
            ],
        ),
        migrations.CreateModel(
            name='Despejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nome_ocupacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome da ocupação')),
                ('num_familias', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=600, null=True, verbose_name='endereço da ocupação')),
                ('situacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='situação')),
                ('pandemia', models.CharField(blank=True, max_length=10, null=True, verbose_name='despejo durante a pandemia')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição do despejo')),
                ('data_existencia', models.DateField(blank=True, null=True, verbose_name='data de existência da ocupação')),
                ('data_ameaca_despejo', models.DateField(blank=True, null=True, verbose_name='data de ameaça do despejo')),
                ('data_para_despejo', models.DateField(blank=True, null=True, verbose_name='data marcada para o despejo')),
                ('carater_imovel', models.CharField(blank=True, max_length=100, null=True, verbose_name='caráter do imóvel')),
                ('tipologia', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipologia')),
                ('zona', models.CharField(blank=True, max_length=100, null=True, verbose_name='zona')),
                ('responsavel_despejo', models.CharField(blank=True, max_length=100, null=True, verbose_name='responsável pelo despejo')),
                ('motivo_despejo', models.CharField(blank=True, max_length=500, null=True, verbose_name='motivo para o despejo')),
                ('cod_acao_justica', models.CharField(blank=True, max_length=100, null=True, verbose_name='código da ação na justica')),
                ('link_sobre_despejo', models.CharField(blank=True, max_length=500, null=True, verbose_name='link sobre o despejo')),
                ('assessoria_juridica', models.CharField(blank=True, max_length=200, null=True, verbose_name='assessoria jurídica')),
                ('movimento_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='movimento social')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despejos', to='despejos.cidade', verbose_name='cidade')),
            ],
        ),
    ]
