# Generated by Django 3.1.7 on 2021-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despejos', '0003_auto_20210520_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerdefinition',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
