# Generated by Django 3.1.7 on 2021-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despejos', '0004_layerdefinition_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerdefinition',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
